apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-default
spec:
    restartPolicy: Always
    nodeSelector:
      kubernetes.io/hostname: 10.11.12.66
    containers:
    - name: ubuntu-default
      image: ubuntu:16.04
      command: ["/bin/bash"]
      stdin: true
      tty: true
      resources:
        limits:
            cpu: 10
            memory: "2Gi"
        requests:
            cpu: 10
            memory: "2Gi"
        resizePolicy:
            cpu: "LiveResizable"
            memory: "LiveResizable"
